# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TemperatureService.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'TemperatureService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18TemperatureService.proto\x12\x13temperature_service\"c\n\x12TemperatureAverage\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x11\n\tavg_value\x18\x02 \x01(\x01\x12\x14\n\x0csample_count\x18\x03 \x01(\r\x12\x11\n\tsensor_id\x18\x04 \x01(\t\"P\n\x16TemperatureAverageList\x12\x36\n\x05items\x18\x01 \x03(\x0b\x32\'.temperature_service.TemperatureAverage\"-\n\tTimeRange\x12\x10\n\x08start_ts\x18\x01 \x01(\x01\x12\x0e\n\x06\x65nd_ts\x18\x02 \x01(\x01\"\x1b\n\nCountReply\x12\r\n\x05\x63ount\x18\x01 \x01(\r\"\x0e\n\x0c\x45mptyMessage2\x9a\x03\n\x12TemperatureService\x12`\n\x10GetLatestAverage\x12!.temperature_service.EmptyMessage\x1a\'.temperature_service.TemperatureAverage\"\x00\x12\x66\n\x15GetHistoricalAverages\x12\x1e.temperature_service.TimeRange\x1a+.temperature_service.TemperatureAverageList\"\x00\x12\x63\n\x0fListAllAverages\x12!.temperature_service.EmptyMessage\x1a+.temperature_service.TemperatureAverageList\"\x00\x12U\n\rCountAverages\x12!.temperature_service.EmptyMessage\x1a\x1f.temperature_service.CountReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TemperatureService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPERATUREAVERAGE']._serialized_start=49
  _globals['_TEMPERATUREAVERAGE']._serialized_end=148
  _globals['_TEMPERATUREAVERAGELIST']._serialized_start=150
  _globals['_TEMPERATUREAVERAGELIST']._serialized_end=230
  _globals['_TIMERANGE']._serialized_start=232
  _globals['_TIMERANGE']._serialized_end=277
  _globals['_COUNTREPLY']._serialized_start=279
  _globals['_COUNTREPLY']._serialized_end=306
  _globals['_EMPTYMESSAGE']._serialized_start=308
  _globals['_EMPTYMESSAGE']._serialized_end=322
  _globals['_TEMPERATURESERVICE']._serialized_start=325
  _globals['_TEMPERATURESERVICE']._serialized_end=735
# @@protoc_insertion_point(module_scope)
