# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import TemperatureService_pb2 as TemperatureService__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in TemperatureService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TemperatureServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLatestAverage = channel.unary_unary(
                '/temperature_service.TemperatureService/GetLatestAverage',
                request_serializer=TemperatureService__pb2.EmptyMessage.SerializeToString,
                response_deserializer=TemperatureService__pb2.TemperatureAverage.FromString,
                _registered_method=True)
        self.GetHistoricalAverages = channel.unary_unary(
                '/temperature_service.TemperatureService/GetHistoricalAverages',
                request_serializer=TemperatureService__pb2.TimeRange.SerializeToString,
                response_deserializer=TemperatureService__pb2.TemperatureAverageList.FromString,
                _registered_method=True)
        self.ListAllAverages = channel.unary_unary(
                '/temperature_service.TemperatureService/ListAllAverages',
                request_serializer=TemperatureService__pb2.EmptyMessage.SerializeToString,
                response_deserializer=TemperatureService__pb2.TemperatureAverageList.FromString,
                _registered_method=True)
        self.CountAverages = channel.unary_unary(
                '/temperature_service.TemperatureService/CountAverages',
                request_serializer=TemperatureService__pb2.EmptyMessage.SerializeToString,
                response_deserializer=TemperatureService__pb2.CountReply.FromString,
                _registered_method=True)


class TemperatureServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLatestAverage(self, request, context):
        """Retorna a média de temperatura mais recente
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoricalAverages(self, request, context):
        """Retorna médias de temperatura num intervalo de tempo (timestamps em epoch seconds)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllAverages(self, request, context):
        """Lista todas as médias já armazenadas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountAverages(self, request, context):
        """Quantas médias estão armazenadas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemperatureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLatestAverage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestAverage,
                    request_deserializer=TemperatureService__pb2.EmptyMessage.FromString,
                    response_serializer=TemperatureService__pb2.TemperatureAverage.SerializeToString,
            ),
            'GetHistoricalAverages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoricalAverages,
                    request_deserializer=TemperatureService__pb2.TimeRange.FromString,
                    response_serializer=TemperatureService__pb2.TemperatureAverageList.SerializeToString,
            ),
            'ListAllAverages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllAverages,
                    request_deserializer=TemperatureService__pb2.EmptyMessage.FromString,
                    response_serializer=TemperatureService__pb2.TemperatureAverageList.SerializeToString,
            ),
            'CountAverages': grpc.unary_unary_rpc_method_handler(
                    servicer.CountAverages,
                    request_deserializer=TemperatureService__pb2.EmptyMessage.FromString,
                    response_serializer=TemperatureService__pb2.CountReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'temperature_service.TemperatureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('temperature_service.TemperatureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TemperatureService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLatestAverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperature_service.TemperatureService/GetLatestAverage',
            TemperatureService__pb2.EmptyMessage.SerializeToString,
            TemperatureService__pb2.TemperatureAverage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoricalAverages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperature_service.TemperatureService/GetHistoricalAverages',
            TemperatureService__pb2.TimeRange.SerializeToString,
            TemperatureService__pb2.TemperatureAverageList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllAverages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperature_service.TemperatureService/ListAllAverages',
            TemperatureService__pb2.EmptyMessage.SerializeToString,
            TemperatureService__pb2.TemperatureAverageList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountAverages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperature_service.TemperatureService/CountAverages',
            TemperatureService__pb2.EmptyMessage.SerializeToString,
            TemperatureService__pb2.CountReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
